import item1_1 from "../assets/images/item1_1.webp";
import item1_2 from "../assets/images/item1_2.webp";
import item2 from "../assets/images/item2.webp";
import item3_1 from "../assets/images/item3_1.webp";
import item3_2 from "../assets/images/item3_2.webp";
import item3_3 from "../assets/images/item3_3.webp";
import item3_4 from "../assets/images/item3_4.webp";
import item3_5 from "../assets/images/item3_5.webp";
import item3_6 from "../assets/images/item3_6.webp";
import item4_1 from "../assets/images/item4_1.webp";
import item4_2 from "../assets/images/item4_2.webp";
import item4_3 from "../assets/images/item4_3.webp";
import item4_4 from "../assets/images/item4_4.webp";
import item4_5 from "../assets/images/item4_5.webp";
import item4_6 from "../assets/images/item4_6.webp";
import item5 from "../assets/images/item5.webp";
import item6_1 from "../assets/images/item6_1.webp";
import item6_2 from "../assets/images/item6_2.webp";
import item6_3 from "../assets/images/item6_3.webp";
import item6_4 from "../assets/images/item6_4.webp";
import item7_1 from "../assets/images/item7_1.webp";
import item7_2 from "../assets/images/item7_2.webp";
import item7_3 from "../assets/images/item7_3.webp";
import item7_4 from "../assets/images/item7_4.webp";
import item8_1 from "../assets/images/item8_1.webp";
import item8_2 from "../assets/images/item8_2.webp";
import item8_3 from "../assets/images/item8_3.webp";
import item8_4 from "../assets/images/item8_4.webp";
import item8_5 from "../assets/images/item8_5.webp";
import item9_1 from "../assets/images/item9_1.webp";
import item9_2 from "../assets/images/item9_2.webp";
import item9_3 from "../assets/images/item9_3.webp";
import item9_4 from "../assets/images/item9_4.webp";
import item10_1 from "../assets/images/item10_1.webp";
import item10_2 from "../assets/images/item10_2.webp";
import item10_3 from "../assets/images/item10_3.webp";

const ITEMDATA = [
  {
    id: 1,
    username: "흐이",
    temp: "54.8",
    title: "LG TV",
    images: [item1_1, item1_2],
    category: "생활가전",
    date: "3일 전",
    price: "50,000",
    place: "서울 동대문구 휘경제2동",
    content:
      "엘지 텔레비전 입니다. <br/> 고장없어요. 사이즈는 사진 참고해주세요. <br/> 스마트 티비는 아니예요.",
    likes: "15",
    chats: "17",
    views: "690",
  },
  {
    id: 2,
    username: "구름",
    temp: "37.3",
    title: "먹태깡 팔아요 5봉 있어요",
    images: [item2],
    category: "기타 중고물품",
    date: "7일 전",
    price: "1,000",
    place: "경남 진주시 초전동",
    content:
      "파격 세일 천원!! 그리고 기분내키면 500원에 팔게여 <br/> 9월7일 오후 5시에 샀습니다",
    likes: "11",
    chats: "45",
    views: "1549",
  },
  {
    id: 3,
    username: "회계쟁이",
    temp: "38.7",
    title: "다이슨 V8 카본 파이퍼 청소기 팝니다",
    images: [item3_1, item3_2, item3_3, item3_4, item3_5, item3_6],
    category: "생활가전",
    date: "7일 전",
    price: "30,000",
    place: "서울 영등포구 여의도동",
    content:
      "다이슨 V8 카본 파이퍼 청소기 팝니다 <br/> 현재 배터리는 고장난상태로 풀 충전해도 지속시간 약 5초가량입니다 <br/> 다이슨에서 배터리 교체비용 약 9.9만원으로 확인하였습니다 <br/> (배터리 배송오면 직접 교체해야된다고 했습니다) <br/> <br/> 구매가 약 48만원이며 구매시기 20년 12월입니다 <br/> 부속품 다 있고(3번째 사진), 다이슨 가방도 있습니다 <br/> 부속품은 아예 사용하지않아서 다 새거입니다 <br/> 본체의 흠집부분은 참고하세요~(2번째 사진) <br/> <br/> 선유초앞직거래나 문고리거래 원합니다 <br/> 채팅주세요~",
    likes: "7",
    chats: "12",
    views: "1138",
  },
  {
    id: 4,
    username: "빠인씨니",
    temp: "36.9",
    title: "결혼준비로 살림살이 정리 합니다.",
    images: [item4_1, item4_2, item4_3, item4_4, item4_5, item4_6],
    category: "생활/주방",
    date: "4일 전",
    price: "30,000",
    place: "경기도 평택시 고덕동",
    content:
      "10인용전기밥솥,휴롬1세대,건조대,오븐,에어프라이어,화장대. <br/> 중고인 만큼 사용감 당연히 있고,정상작동 합니다. 일괄3만에 가져가세요.",
    likes: "18",
    chats: "23",
    views: "1541",
  },
  {
    id: 5,
    username: "서윤",
    temp: "39.1",
    title: "크록스",
    images: [item5],
    category: "여성잡화",
    date: "7일 전",
    price: "10,000",
    place: "울산 남구 신정5동",
    content:
      "어제 택배 받았는데 사이즈가 맞질않네요 <br/> 교환비 들어서 걍 팔아요 <br/> 싼 가격 이다 보니 환불안됩니다",
    likes: "9",
    chats: "4",
    views: "849",
  },
  {
    id: 6,
    username: "plain",
    temp: "40.2",
    title: "루이비통 가방",
    images: [item6_1, item6_2, item6_3, item6_4],
    category: "여성잡화",
    date: "2일 전",
    price: "98,000",
    place: "경기도 고양시 일산동구 장항동",
    content: "루이비통 가방",
    likes: "43",
    chats: "16",
    views: "1041",
  },
  {
    id: 7,
    username: "슈지니",
    temp: "38.5",
    title: "LG통돌이세탁기",
    images: [item7_1, item7_2, item7_3, item7_4],
    category: "생활가전",
    date: "7일 전",
    price: "100,000",
    place: "경남 밀양시 삼문동",
    content:
      "LG통돌이세탁기 팝니다 15kg구요~ <br/> 이사하면서 가전을 다 새로사서 팔아요 <br/> 고장난데 없고 세탁잘돼요! <br/> 찝찝하심 거름망필터만 교체하셔도 될것같아요",
    likes: "2",
    chats: "11",
    views: "337",
  },
  {
    id: 8,
    username: "하이하이",
    temp: "36.8",
    title: "아이폰 12mini 블랙",
    images: [item8_1, item8_2, item8_3, item8_4, item8_5],
    category: "디지털기기",
    date: "3일 전",
    price: "60,000",
    place: "전남 목포시 상동",
    content:
      "-생활기스 있음 <br/> -액정 아래부분만 조금 깨짐 <br/> -카메라 아래쪽 깨짐 <br/> -배터리 성능 : 78% <br/> -128GB <br/> 사용하는데 큰 지장은 없음 카메라가 흐릿함",
    likes: "12",
    chats: "8",
    views: "781",
  },
  {
    id: 9,
    username: "감자누나",
    temp: "37.5",
    title: "타이틀리스트 스텐드백",
    images: [item9_1, item9_2, item9_3, item9_4],
    category: "스포츠/레저",
    date: "17시간 전",
    price: "70,000",
    place: "서울 송파구 삼전동",
    content:
      "올해 구매가 38만원 주고 직구로 샀어요 <br/> 연습장만 몇번 들고 다니고 필드는 딱 한번 가지고 나갔어요 <br/> 저랑은 골프가 맞지 않는거 같아 싸게 처분합니다 택배는 박스가 여의치 않아 직접거래 원해요",
    likes: "8",
    chats: "7",
    views: "297",
  },
  {
    id: 10,
    username: "둥둥",
    temp: "38.4",
    title: "삼성 게이밍 노트북",
    images: [item10_1, item10_2, item10_3],
    category: "디지털기기",
    date: "1일 전",
    price: "100,000",
    place: "대구 서구 내당4동",
    content:
      "인터넷 잘 되고 소리도 잘나오고 <br/> 말짱한 노트북 팔아요 !!!! <br/> 구매한지 좀 되서 생활기스 정도야 있어요😅",
    likes: "9",
    chats: "7",
    views: "265",
  },
  {
    id: 11,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 12,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 13,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 14,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 15,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 16,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 17,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 18,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 19,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 20,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 21,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 22,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 23,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 24,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 25,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 26,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 27,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 28,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 29,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
  {
    id: 30,
    username: "00",
    temp: "00",
    title: "00",
    images: [],
    category: "00",
    date: "00",
    price: "00",
    place: "00",
    content: "00",
    likes: "00",
    chats: "00",
    views: "00",
  },
];

export default ITEMDATA;
