export const ContentMock = [
  {
    id: 1,
    title: "이대 곰돌이 키링",
    price: "99999",
    address: "서울 서대문구 대현동",
    likes: "100",
    chats: "23",
  },
  {
    id: 2,
    title: "스페이드클럽서울 볼캡",
    price: "20000",
    address: "경기도 고양시 일산동구 마두동",
    likes: "7",
    chats: "2",
  },
  {
    id: 3,
    title: "베트남 과자",
    price: "5000",
    address: "서울 서초구 서초1동",
    likes: "2",
    chats: "1",
  },
  {
    id: 4,
    title: "초록스튜디오 백팩",
    price: "50000",
    address: "인천 서구 백석동",
    likes: "12",
    chats: "3",
  },
  {
    id: 5,
    title: "로지텍 무선마우스",
    price: "15000",
    address: "경북 구미시 인동동",
    likes: "9",
    chats: "2",
  },
  {
    id: 6,
    title: "아이소이 스팟패드",
    price: "12000",
    address: "대전 중구 태평동",
    likes: "4",
    chats: "0",
  },
  {
    id: 7,
    title: "화분 2개",
    price: "20000",
    address: "경기도 고양시 일산동구 장항동",
    likes: "20",
    chats: "3",
  },
  {
    id: 8,
    title: "조던1 줌에어컴포트 짐레드블랙",
    price: "110000",
    address: "부산 북구 덕천제1동",
    likes: "15",
    chats: "2",
  },
  {
    id: 9,
    title: "보조배터리",
    price: "10000",
    address: "서울 동대문구 제기동",
    likes: "8",
    chats: "1",
  },
];
