export const ContentMock = [
  {
    id: 0,
    title: "이대 곰돌이 키링",
    price: "99999",
    address: "서울 서대문구 대현동",
    likes: "100",
    chats: "23",
    temp: "36.5",
    category: "패션",
    time: "방금",
    views: "200",
    explain:
      "이화여자대학교 다우리 곰돌이 키링입니다. 아주 귀여워요. 상태 최상",
    username: "규빈",
  },
  {
    id: 1,
    title: "스페이드클럽서울 볼캡",
    price: "20000",
    address: "경기도 고양시 일산동구 마두동",
    likes: "7",
    chats: "2",
    temp: "36.5",
    category: "패션",
    time: "18 시간 전",
    views: "200",
    explain: "2번 썼는데 안 어울리네요. 싸게 내놓았으니 얼른 가져가세요~",
    username: "규규",
  },
  {
    id: 2,
    title: "베트남 과자",
    price: "5000",
    address: "서울 서초구 서초1동",
    likes: "2",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "1주 전",
    views: "200",
    explain: "제 입맛엔 안 맞아서 판매합니다. 희귀템일걸요..?",
    username: "ㅇㅇ",
  },
  {
    id: 3,
    title: "초록스튜디오 백팩",
    price: "50000",
    address: "인천 서구 백석동",
    likes: "12",
    chats: "3",
    temp: "36.5",
    category: "패션",
    time: "3일 전",
    views: "200",
    explain: "애착 가방인데 급전 필요해서 팝니다ㅠㅠ",
    username: "예",
  },
  {
    id: 4,
    title: "로지텍 무선마우스",
    price: "15000",
    address: "경북 구미시 인동동",
    likes: "9",
    chats: "2",
    temp: "36.5",
    category: "패션",
    time: "2달 전",
    views: "200",
    explain: "제곧내",
    username: "규빈",
  },
  {
    id: 5,
    title: "아이소이 스팟패드",
    price: "12000",
    address: "대전 중구 태평동",
    likes: "4",
    chats: "0",
    temp: "36.5",
    category: "패션",
    time: "5시간 전",
    views: "200",
    explain: "선물 받았는데 필요 없어서 팝니다. 효과 좋은 듯요~^^",
    username: "규빈",
  },
  {
    id: 6,
    title: "화분 2개",
    price: "20000",
    address: "경기도 고양시 일산동구 장항동",
    likes: "20",
    chats: "3",
    temp: "36.5",
    category: "패션",
    time: "1일 전",
    views: "200",
    explain: "엄마가 애지중지 키우신 화분..",
    username: "규빈",
  },
  {
    id: 7,
    title: "조던1 줌에어컴포트 짐레드블랙",
    price: "110000",
    address: "부산 북구 덕천제1동",
    likes: "15",
    chats: "2",
    temp: "36.5",
    category: "패션",
    time: "7시간 전",
    views: "200",
    explain: "연락주세요~!",
    username: "규빈",
  },
  {
    id: 8,
    title: "보조배터리",
    price: "10000",
    address: "서울 동대문구 제기동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "3주 전",
    views: "200",
    explain: "용량 대박입니다. 대학생 필수템:)",
    username: "규빈",
  },
  {
    id: 9,
    title: "보조배터리",
    price: "10000",
    address: "경남 진주시 계동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "22시간 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 10,
    title: "보조배터리",
    price: "10000",
    address: "경기도 평택시 고덕동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "5일 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 11,
    title: "보조배터리",
    price: "10000",
    address: "대구 서구 평리동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "2년 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 12,
    title: "보조배터리",
    price: "10000",
    address: "인천 서구 검암경서동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "2주 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 13,
    title: "보조배터리",
    price: "10000",
    address: "광주 서구 화정1동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "30일 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 14,
    title: "보조배터리",
    price: "10000",
    address: "경기도 파주시 야당동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "3달 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 15,
    title: "보조배터리",
    price: "10000",
    address: "경기도 남양주시 화도읍",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "2일 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 16,
    title: "보조배터리",
    price: "10000",
    address: "대전 동구 용전동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "2시간 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 17,
    title: "보조배터리",
    price: "10000",
    address: "전북 전주시 덕진구 우아2동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "2주 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 18,
    title: "보조배터리",
    price: "10000",
    address: "경북 경산시 갑제동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "3달 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 19,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "1시간 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 20,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "2주 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 21,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "2일 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 22,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "8달 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 23,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "1년 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 24,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "9시간 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 25,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "2주 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 26,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "6일 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 27,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "3주 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 28,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "방금",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
  {
    id: 29,
    title: "보조배터리",
    price: "10000",
    address: "전남 목포시 상동",
    likes: "8",
    chats: "1",
    temp: "36.5",
    category: "패션",
    time: "12시간 전",
    views: "200",
    explain: "연락주쇼",
    username: "규빈",
  },
];
