export const ProductData = [
    {
        id: 1,
        name: "아내가 제 아이패드 팔아서",
        price: "700,000",
        place: "서울 동대문구 휘경제2동",
        cart: "관심 86 ∙ 채팅 105",
        sellerName: "우진우빈파더",
        temp: "36.8°C",
        category: "기타 중고물품 ∙ 3일전",
        detail: "진품은 맞고요 얼마인지는 모르겠고 아내가 제 아이패드 마음대로 팔아서 저도 똑같이 샤넬백 팝니다. 다시 돌려달라고 안할거고요 아내도요.",
        interest: "관심 86 ∙ 채팅 105 ∙ 조회 3260",
    },
    {
        id: 2,
        name: "베이비젠 요요2",
        price: "150,000",
        place: "서초구 잠원동",
        cart: "관심 19 ∙ 채팅 16",
        sellerName: "샌드뱅크",
        temp: "42.2°C",
        category: "유아동 ∙ 13시간 전",
        detail: `22년 신세계 강남점 팝업스토어에서 구매했고요
        1년정도 잘 사용했습니다. 다른제품으로 갈아타면서 정리합니다.
        유모차 및 악세서리 포함되어 있습니다
        방풍레인커버 / 방한커버
        모기장 2개 (미사용정품,호환되는 타제품)
        뒷바퀴있고 요요백, 작은 백 있습니다
        사용감은 좀 있는데 바퀴나 동작에 문제 없습니다`,
        interest: "관심 19 ∙ 채팅 16 ∙ 조회 404",
    },
    {
        id: 3,
        name: "i7-7700 컴퓨터",
        price: "60,000",
        place: "화성시 동탄8동",
        cart: "관심 13 ∙ 채팅 19",
        sellerName: "마당",
        temp: "41.3°C",
        category: "디지털기기 ∙ 14시간 전",
        detail: `CPU; i7-7700 3.6GHz
        RAM; DDR4 8G
        OS; HDD에 Windows11 정품 인증 완료 재 설치 시 WINDOW 7 번호 사용
        그래픽 카드; Geforce GTX1050 OC2G
        메인보드; GIGABYTE GA-B150M-DS3H
        M.2 NVMe 32GhZ 소켓이 있어 차후 별도 구입 후 window 성능 향상 가능`,
        interest: "관심 13 ∙ 채팅 19 ∙ 조회 284",
    },
    {
        id: 4,
        name: "코웨이 제습기",
        price: "40,000",
        place: "청주시 청원구 오창읍",
        cart: "관심 6 ∙ 채팅 9",
        sellerName: "느을72",
        temp: "71.2°C",
        category: "생활가전 ∙ 13시간 전",
        detail: `몇해전 구매 후 한 두해 사용하다 보관만한 제습기 입니다.
        이사기기전에 판매합니다.
        어제 test해봤는데 잘 작동되구 제습성능도 좋습니다.
        사용설명서두 있구요
        잘 닦아 드리겠습니다`,
        interest: "관심 6 ∙ 채팅 9 ∙ 조회 340",
    },
    {
        id: 5,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 6,
        name: "예초기",
        price: "50,000",
        place: "청주시 흥덕구 봉명2.송정동",
        cart: "관심 7 ∙ 채팅 16",
        sellerName: "황소",
        temp: "36.9°C",
        category: "기타 중고물품 ∙ 13시간 전",
        detail: `2-3년 사용하지안아 시동이 안됨, 반품안됨니다, 네고없슴니다,
        봉명동 543-13 으로
        09시까지 선착순으로 가져가시면 됩니다`,
        interest: "관심 7 ∙ 채팅 16 ∙ 조회 759",
    },
    {
        id: 7,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 8,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 9,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 10,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 11,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 12,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 13,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 14,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 15,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 16,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 17,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 18,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 19,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 20,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
    {
        id: 21,
        name: "베트남동 205만8천동팝니다",
        price: "112,000",
        place: "강서구 등촌제2동",
        cart: "관심 1 ∙ 채팅 13",
        sellerName: "is",
        temp: "36.5°C",
        category: "티켓/교환권 ∙ 5일 전",
        detail: `등촌역 7~8번출구에서 거래합니다`,
        interest: "관심 1 ∙ 채팅 13 ∙ 조회 302",
    },
];
